name: CI PS4/ORBIS

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add ncurses-dev make bash python2
        apk add libintl icu-dev wget
    
    - name: Compile RA
      working-directory: ./itemzflow
      run: ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: bin-${{ steps.slug.outputs.sha8 }}
        path: ./bin/
