name: CI PS4/ORBIS

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add ncurses-dev wget
    
    - name: Compile RA
      working-directory: ./itemzflow
      run: ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: bin
        path: ./bin/
