name: CI PS4/ORBIS

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add ncurses-dev make wget git

    - name: Compile libdumper
      working-directory: ./external/libdumper
      run: |
        make -j$(nproc)

    - name: Compile libfuse
      working-directory: ./external/libfuse
      run: |
        make -j$(nproc)

    - name: Compile taglib
      working-directory: ./external/taglib
      run: |
        make -j$(nproc)

    - name: Get libyaml-cpp
      run: git clone https://github.com/jasonjei/libyaml-cpp
  
    - name: Compile Itemzflow
      working-directory: ./itemzflow
      run: |
        chmod +x ./build.sh
        ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: bin
        path: ./bin/
