name: CI PS4/ORBIS

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

env:
  PS4SDK: '/usr/local/orbisdev'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add ncurses-dev make wget git
  
    - name: Clone Itemzflow
      uses: actions/checkout@v4

    - name: Clone liborbis
      uses: actions/checkout@v4
      with:
        repository: orbisdev/liborbis
        path: external/liborbis

    - name: Install liborbis
      working-directory: ./external/liborbis
      run: |
        make clean all install

    - name: Build libdumper
      working-directory: ./external/libdumper
      run: |
        make -j$(nproc)
        make install

    - name: Build libfuse
      working-directory: ./external/libfuse
      run: |
        make -j$(nproc)
        make install

    - name: Compile taglib
      working-directory: ./external/taglib
      run: |
        make -j$(nproc)
        make install

    - name: Compile Itemz daemon
      working-directory: ./itemz-daemon
      run: |
        make -j$(nproc)
        make oelf
        make eboot

    - name: Compile Itemzflow
      working-directory: ./itemzflow
      run: |
        make -j$(nproc)
        make oelf
        make eboot
        make pkg_build

    - uses: actions/upload-artifact@v4
      with:
        name: bin
        path: ./bin/
